if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

source 'https://rubygems.org'

gem 'rake', '10.0.3'
gem 'rails', '3.2.21'

group :production, :staging do
  gem 'passenger'
  gem 'newrelic_rpm'
end
